id: somethink
branches:
  main:
    type: set
    data: ["1"]
unexpected: exception